version: 2

models:
  - name: dim_locations
    columns:
      - name: cod_location
        tests:
          - not_null
          - unique

  - name: dim_date
    columns:
      - name: id
        tests:
          - not_null
          - unique

  - name: fact_weather
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: cod_location
        tests:
          - relationships:
              to: ref('dim_locations')
              field: cod_location
      - name: date_id
        tests:
          - relationships:
              to: ref('dim_date')
              field: id
      - name: temperature_max
        tests:
          - not_null
      - name: temperature_min
        tests:
          - not_null
      - name: temperature_mean
        tests:
          - not_null
      - name: precipitation_sum
        tests:
          - not_null